Run distribution with repo-root dk0

diff --git a/.github/workflows/distribute-2.5.yml b/.github/workflows/distribute-2.5.yml
--- a/.github/workflows/distribute-2.5.yml
+++ b/.github/workflows/distribute-2.5.yml
@@ -67,20 +67,175 @@ jobs:
         if: ${{ matrix.distscript == 'dist-Linux_x86.u' }}
         run: dnf install -y glibc-devel.i686 libgcc.i686 libstdc++.i686 gcc-toolset-14-libstdc++-devel.i686
 
-      - name: Distribute Modules
-        uses: diskuv/dk-distribute@v2
+      - name: Check if bwrap available for sandboxing
+        id: check-bwrap
+        if: ${{ matrix.experimental-mlfront-ref }}
+        shell: bash
+        run: |
+          if [ "${{ runner.os }}" != "Linux" ]; then
+            echo "disable_sandboxing=false" | tee -a "$GITHUB_OUTPUT"
+            exit 0
+          fi
+          if command -v bwrap > /dev/null 2>&1; then
+            echo "disable_sandboxing=false" | tee -a "$GITHUB_OUTPUT"
+          else
+            echo "disable_sandboxing=true" | tee -a "$GITHUB_OUTPUT"
+          fi
+
+      - name: Set-up OCaml
+        if: ${{ matrix.experimental-mlfront-ref }}
+        uses: ocaml/setup-ocaml@57d9aa353e8d39677b1b9fc39637d48f27fe4a91 # v3
         with:
-            pubkey: ${{ secrets.distribute_2_5_pubkey }}
-            seckey: ${{ secrets.distribute_2_5_seckey }}
-            id: CommonsBase_FileMagic@${{ github.ref_name }}
-            options: -nosysinc -I etc/dk/i
-            use-cache: true
-            distscript: ${{ matrix.distscript }}
-            experimental-dk-owner: ${{ github.repository_owner == 'dkpkg' && 'diskuv' || github.repository_owner }}
-            #   Use MlFront HEAD when CI build is not from a tag. But if matrix says it is true, always use HEAD.
-            experimental-mlfront-ref: ${{ (github.ref_type != 'tag' || matrix.experimental-mlfront-ref) && 'HEAD' }}
-            #   Uncomment when testing MlFront
-            # experimental-mlfront-ref: HEAD
+          ocaml-compiler: 5.4.0
+          opam-disable-sandboxing: ${{ steps.check-bwrap.outputs.disable_sandboxing == 'true' }}
+          opam-repositories: |
+            default: git+https://github.com/ocaml/opam-repository.git#93d44806c4a413399879355cb22fb53ba00a1ba5
+          cache-prefix: dk-distribute-v2
+
+      - name: Get MlFront
+        if: ${{ matrix.experimental-mlfront-ref }}
+        shell: bash
+        run: |
+          git clone https://gitlab.com/dkml/build-tools/MlFront.git
+          cd MlFront
+          git reset --hard HEAD
+
+          sh ci/localize-pristine.sh
+          git config user.email "nobody@example.com"
+          git config user.name "nobody"
+          git add --force dune-project *.opam
+          git commit -m "pristine"
+
+      - name: Pin Latest MlFront
+        if: ${{ matrix.experimental-mlfront-ref }}
+        shell: bash
+        run: cd MlFront && opam pin . --no-action -y
+
+      - name: Install DkZero_Exec
+        if: ${{ matrix.experimental-mlfront-ref }}
+        shell: bash
+        run: cd MlFront && opam install ./DkZero_Exec.opam -y
+
+      - name: Create repository dk0 wrapper on Unix
+        if: ${{ runner.os != 'Windows' && matrix.experimental-mlfront-ref }}
+        shell: bash
+        run: |
+          printf '#!/bin/sh\nset -euf\nopam exec -- dk0 "$@"\n' > .ci-dk0
+          chmod +x .ci-dk0
+
+      - name: Cache restore dk stores
+        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
+        id: restore-cache-dk-distribute
+        with:
+          enableCrossOsArchive: true
+          path: t
+          key: dk-stores-and-keys-x1-2.5-${{ github.run_id }}
+          restore-keys: dk-stores-and-keys-x1-2.5
+
+      - name: Distribute Modules on Unix
+        if: ${{ runner.os != 'Windows' }}
+        shell: bash
+        env:
+          GH_TOKEN: ${{ github.token }}
+          DK_BUILD_PUBKEY: "${{ secrets.distribute_2_5_pubkey }}"
+          DK_BUILD_SECKEY: "${{ secrets.distribute_2_5_seckey }}"
+        run: |
+          if [ "${{ matrix.experimental-mlfront-ref }}" = "true" ]; then
+            DK0=./.ci-dk0
+          else
+            DK0=./dk0
+          fi
+          PART='${{ matrix.distscript }}'
+          PART="${PART%%.*}"
+
+          rm -rf etc/dk/i
+          echo "$DK0 --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD update"
+          "$DK0" --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD update
+
+          echo "$DK0 --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD --verbose distribute CommonsBase_FileMagic-$PART --library CommonsBase_FileMagic@${{ github.ref_name }} ${{ matrix.distscript }}"
+          "$DK0" --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD --verbose distribute CommonsBase_FileMagic-"$PART" --library CommonsBase_FileMagic@${{ github.ref_name }} ${{ matrix.distscript }}
+
+          du -sh dk-dist/*
+
+      - name: Query traces on Unix
+        if: ${{ runner.os != 'Windows' }}
+        shell: bash
+        env:
+          DK_BUILD_PUBKEY: "${{ secrets.distribute_2_5_pubkey }}"
+          DK_BUILD_SECKEY: "${{ secrets.distribute_2_5_seckey }}"
+          OCAMLRUNPARAM: b
+        run: |
+          if [ "${{ matrix.experimental-mlfront-ref }}" = "true" ]; then
+            DK0=./.ci-dk0
+          else
+            DK0=./dk0
+          fi
+          "$DK0" --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD query
+
+      - name: Distribute Modules on Windows
+        if: ${{ runner.os == 'Windows' }}
+        shell: pwsh
+        env:
+          GH_TOKEN: ${{ github.token }}
+          DK_BUILD_PUBKEY: "${{ secrets.distribute_2_5_pubkey }}"
+          DK_BUILD_SECKEY: "${{ secrets.distribute_2_5_seckey }}"
+        run: |
+          $part = '${{ matrix.distscript }}'
+          $part = $part.Substring(0, $part.LastIndexOf('.'))
+          if (Test-Path etc/dk/i) { Remove-Item -Recurse -Force etc/dk/i }
+
+          Write-Host ".\dk0.cmd --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD update"
+          .\dk0.cmd --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD update
+          if ($LASTEXITCODE -ne 0) {
+            throw "dk0 update failed with exit code $LASTEXITCODE"
+          }
+
+          Write-Host ".\dk0.cmd --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD --verbose distribute CommonsBase_FileMagic-$part --library CommonsBase_FileMagic@${{ github.ref_name }} ${{ matrix.distscript }}"
+          .\dk0.cmd --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD --verbose distribute CommonsBase_FileMagic-$part --library CommonsBase_FileMagic@${{ github.ref_name }} ${{ matrix.distscript }}
+          if ($LASTEXITCODE -ne 0) {
+            throw "dk0 distribute failed with exit code $LASTEXITCODE"
+          }
+
+          Get-ChildItem -Directory dk-dist | ForEach-Object {
+            $size = (Get-ChildItem $_.FullName -Recurse -File | Measure-Object -Property Length -Sum).Sum
+            $sizeGB = [math]::Round($size / 1GB, 2)
+            Write-Output "$($sizeGB) GB`t$($_.Name)"
+          }
+
+      - name: Query traces on Windows
+        if: ${{ runner.os == 'Windows' }}
+        shell: pwsh
+        env:
+          DK_BUILD_PUBKEY: "${{ secrets.distribute_2_5_pubkey }}"
+          DK_BUILD_SECKEY: "${{ secrets.distribute_2_5_seckey }}"
+          OCAMLRUNPARAM: b
+        run: |
+          .\dk0.cmd --errors-plain -nosysinc -I etc/dk/i --keys-env DK_BUILD query
+          if ($LASTEXITCODE -ne 0) {
+            throw "dk0 query failed with exit code $LASTEXITCODE"
+          }
+
+      - name: Save logs
+        if: always()
+        uses: actions/upload-artifact@v7
+        with:
+          name: logs-${{ matrix.distscript }}
+          path: t/p/*/*/l/*/
+
+      - name: Share distribution artifacts
+        if: success()
+        uses: actions/upload-artifact@v7
+        with:
+          name: distribution-${{ matrix.distscript }}
+          path: dk-dist/
+
+      - name: Cache save dk stores
+        if: steps.restore-cache-dk-distribute.outputs.cache-hit == ''
+        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
+        with:
+          enableCrossOsArchive: true
+          path: t
+          key: dk-stores-and-keys-x1-2.5-${{ github.run_id }}
 
   combine:
     needs: distribute
